# Generated by Django 5.0.4 on 2024-04-17 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lineapedido",
            old_name="pedido_id",
            new_name="pedido",
        ),
        migrations.RenameField(
            model_name="lineapedido",
            old_name="producto_id",
            new_name="producto",
        ),
    ]
