# Generated by Django 5.0.4 on 2024-04-17 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Pedidos", "0003_alter_lineapedido_options_alter_pedido_options_and_more"),
    ]

    operations = []
