# Generated by Django 5.0.4 on 2024-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestionPedidos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientes",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
