# Generated by Django 5.0.4 on 2024-04-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tienda", "0002_producto_created_producto_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
