# Generated by Django 5.0.4 on 2024-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Tienda", "0003_alter_producto_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="catproducto",
            options={
                "verbose_name": "categoriaPro",
                "verbose_name_plural": "categoriasProd",
            },
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.FloatField(),
        ),
    ]
